### ISSUE TITLE
Error while getting B2 upload details: Request failed with status code 401

### ISSUE THREAD

**Issue by oneandonlyjason** [mattwelke/upload-file-to-backblaze-b2-from-browser-example#306]
Is this Still Working?

I cloned the Repository, edited the Backend Config with the needed Details, did npm install and then npm start

When i then access http://localhost:3000/getUploadDetails i get the Error in the Title in my Console

Could you maybe test if this is still working?

**Comment by mattwelke** [comment]
Yep, when I run it and follow the instructions in the README, it doesn't work. I see a CORS error when the front end app tries to use the response from the back end app for `getUploadDetails`:

![image](https://user-images.githubusercontent.com/7719209/163885724-73a89e67-0f61-4a7d-bda3-2f14b5d6d82a.png)

Is that what was happening for you too?

**Comment by oneandonlyjason** [comment]
Yeah i also get the 500 Server Error when getUploadDetails is getting accessed + the Mentioned Error in the Log / Console where the NPM App is running

**Comment by mattwelke** [comment]
So the reason this was confusing to figure out what was going on is because of a classic CORS mistake I used to make, apparently when I put this example together. I would remember to set the `Access-Control-Allow-Origin` header on the happy path, but not on the error path. In this case, an error is thrown by the function in `getUploadDetails.js` in the backend, which is cause by the request handler, but that `catch` block in the handler doesn't set the CORS header. So the browser knows it was a 500 but has no way of displaying useful information in the frontend.

As for why it isn't working, what I've figured out so far is that for some reason, `bucketId` is null in the response from the "get auth details" step. That was a property the example was relying on before. For some reason, it was present before, but now it isn't.

![image](https://user-images.githubusercontent.com/7719209/163887320-9408bb75-3ff0-41d8-be6b-3e32074a84a6.png)

**Comment by oneandonlyjason** [comment]
This is strange. If I understand the documentation correctly this ID should be present as long as the key only has access to one bucket

**Comment by mattwelke** [comment]
Maybe. I actually wasn't aware of that. It sounds like I may have been careless when originally figuring out how to do this, relying on undocumented behavior. And maybe now they cleaned up their API.

According to what you say, it should be present as long as the key only has access to one bucket, but I have three buckets right now:

![image](https://user-images.githubusercontent.com/7719209/163889098-e0f2e446-5b8b-484f-8d04-8a95d34b4f86.png)

I remember in 2020 someone commented here saying the example wasn't working for them and I was able to test it back then. It worked. So my three buckets back in 2020 weren't causing any problems.

Anyways, I think for this example, it makes sense that the user would provide their bucket ID for the bucket they're instructed to create. I think that would be less error prone. So I'll update the code to use a bucket ID that comes from env var config, like the other two pieces of config data, and update the repo.

Thanks for reporting this.

**Comment by mattwelke** [comment]
Looks like that approach works fine. :tada: :parrot: 

![image](https://user-images.githubusercontent.com/7719209/163890150-7976fcfa-e0ee-4c3e-b606-9a4c7985d237.png)

I got a 500 error from their server for the b2_get_upload_url step when I was stepping through slowly with VS Code, so be advised that their API seems to have short timeouts. If you step through, you'll need to do so with only a few seconds pause between each breakpoint.
